---
- hosts: webservers
  become: yes
  gather_facts: yes
  vars:
    root_path: /var/www/html
    index_format: index.php
    http_port: "80"

  tasks:
    - name: installing servers
      apt:
        name: ['nginx', 'php', 'php-fpm']
        state: latest
        update_cache: yes
      when: ansible_os_family == "Debian"
      
    - name: Removing packages
      apt:
        name: apache2
        state: absent
        purge: yes
        update_cache: yes
      when: ansible_os_family == "Debian"


    - name: template change
      template:
        src: default.j2
        dest: /etc/nginx/sites-available/default

    - name: copy index.php
      copy:
        src: "./{{index_format}}"
        dest: "{{root_path}}/{{index_format}}"
        
    - name: HTTP on port 80 allow
      ufw:
        rule: allow
        port: "{{http_port}}"
        proto: tcp


    - name: restart server 
      service:
        name: nginx
        state: restarted


- hosts: haproxy
  become: yes
  gather_facts: yes
  tasks:
    - name: install haproxy
      apt:
        name: haproxy
        update_cache: yes
        state: latest
      when: ansible_os_family == "Debian"

    - name: change haproxy 
      template:
        src: haproxy.cfg.j2
        dest: /etc/haproxy/haproxy.cfg

    - name: restart haproxy
      service:
        name: haproxy
        state: restarted

    - name: template of rudimentary 
      template:
        src:  rudimentary_test.sh.j2
        dest: $HOME/rudimentary_test.sh

    - name: rudimentary test
      command:  bash $HOME/rudimentary_test.sh
      register: test
      args:
        warn: no
    - debug:
        msg:  "{{test.stdout}}"

