---
- hosts: webservers
  become: yes
  remote_user: ubuntu

  tasks:
 
  - name: nginx installation
    apt:
      name: nginx
      state: present

  - name: php files installation      
    apt:
      name: php
      state: present

  - name: php-fpm installation
    apt:
      name: php-fpm
      state: present

  - name: packages upgrade 
    apt:
      update_cache: yes
      upgrade: dist
      force_apt_get: yes

    notify:
      - start nginx
      - start php-fpm

  - name: remove nginx.conf 
    file:
       path: "/etc/nginx/nginx.conf"
       state: absent
 
  - name: Set nginx.conf 
    template:
       src: "./mynginx.conf"
       dest: "/etc/nginx/nginx.conf"

    notify:
    - restarting php-fpm
    - restarting nginx

  - name: remove present default_file 
    file:
       path: "/etc/nginx/sites-enabled/default"
       state: absent

    notify:
    - restarting nginx

  - name: inserting default 
    template:
       src: "./default"
       dest: "/etc/nginx/sites-available/default1"

  - name: linking default 
    file:
       src: "/etc/nginx/sites-available/default1"
       dest: "/etc/nginx/sites-enabled/default1"
       state: link

    notify:
    - restarting nginx


  - name: inserting index.php in var
    template:
      src: "./index.php"
      dest: "/var/www/html/index.php"

    notify:
    - restarting nginx
    - start nginx
    - restarting php-fpm
    - start php-fpm

  handlers:

  - name: start php-fpm
    service:
      name: php7.4-fpm
      state: started

  - name: start nginx
    service:
      name: nginx
      state: started

  - name: restarting php-fpm
    service:
      name: php7.4-fpm
      state: restarted

  - name: restarting nginx
    service:
      name: nginx

      state: restarted

- hosts: haproxy
  become: true
  remote_user: ubuntu

  tasks:

  - name: haproxy installation
    package:
      name: "haproxy"
      state: present
    register: haproxystatus

  - name: packages upgrade
    apt:
      update_cache: yes
      upgrade: dist
      force_apt_get: yes
    notify:
      - runinng haproxy        


  - name: default_haproxy_cfg removed
    file:
       path: "/etc/haproxy/haproxy.cfg"
       state: absent
    notify:
    - restarting Haproxy 

  - name: haProxy configuration
    template:
      src: ./myhaproxy.cfg.j2
      dest: "/etc/haproxy/haproxy.cfg"
    notify:
      - restarting haproxy
      - runinng haproxy

  handlers:

  - name: runinng haproxy
    service:
      name: haproxy
      state: started

  - name: restarting haproxy
    service:
      name: haproxy
      state: restarted
